class SimpleSegment
  class Client
    def identify: (user_id: ::String user_id, traits: propertiesHash traits) -> void
    def group: (user_id: ::String user_id, group_id: ::String group_id, traits: propertiesHash traits) -> void
    def track: (user_id: ::String user_id, event: ::String event, properties: propertiesHash properties) -> void
    def alias: (user_id: ::String user_id, previous_id: ::String previous_id) -> void

    private

    def initialize: (write_key: ::String write_key, logger: ::Logger logger) -> void
  end
end
