class Itly
  class Plugin
    class Amplitude < Plugin
      VERSION: String

      attr_reader logger: Logger?
      attr_reader disabled: bool

      def load: (options: Itly::PluginOptions options) -> void
      def identify: (user_id: String user_id, properties: propertiesHash, ?options: Itly::Plugin::Amplitude::IdentifyOptions? options) -> void
      def track: (user_id: String user_id, event: Itly::Event event, ?options: Itly::Plugin::Amplitude::TrackOptions? options) -> void

      private

      def initialize: (api_key: String api_key, ?disabled: bool disabled) -> void
      def enabled?: () -> bool
      def call_end_point: ((^(Integer?, String?) -> void)? callback) ?{ () -> Faraday::Response } -> void
    end
  end
end
