class Itly
  class Plugin
    class Amplitude
      class CallOptions < PluginCallOptions
      end

      class IdentifyOptions < CallOptions
      end

      class TrackOptions < CallOptions
      end
    end
  end
end
