AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/FileName:
  Exclude:
    - plugin-amplitude/lib/itly/plugin-amplitude.rb
    - plugin-iteratively/lib/itly/plugin-iteratively.rb
    - plugin-mixpanel/lib/itly/plugin-mixpanel.rb
    - plugin-schema-validator/lib/itly/plugin-schema-validator.rb
    - plugin-schema-validator/lib/itly/plugin-schema_validator.rb
    - plugin-segment/lib/itly/plugin-segment.rb
    - plugin-snowplow/lib/itly/plugin-snowplow.rb
    - sdk/lib/itly-sdk.rb
Style/Documentation:
  Exclude:
    - '*/spec/support/**/*'
Style/Lambda:
  Enabled: false
