AllCops:
  NewCops: enable
Layout/HashAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - sdk/lib/itly-sdk.rb
Style/Documentation:
  Exclude:
    - '*/spec/support/**/*'
Style/Lambda:
  Enabled: false