# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in itly-plugin-amplitude.gemspec
gemspec

gem 'rake', '~> 13.0'

# TODO: before publication to RubyGems, remove this:
gem 'itly-sdk', path: '..'
