class Itly
  class Plugin
    class SchemaValidator < Plugin
      VERSION: ::String

      attr_reader logger: ::Logger
      attr_reader schemas: ::Hash[::String | ::Symbol, untyped]
      attr_reader validators: ::Hash[::Symbol, ::JSONSchemer]?
      attr_reader disabled: bool

      def load: (options: ::Hash[::Symbol, ::Symbol | ::Logger] options) -> void
      def validate: (event: ::Itly::Event event) -> ::Itly::ValidationResponse?

      private

      def initialize: (schemas: ::Hash[::String | ::Symbol, untyped] schemas, ?disabled: bool disabled) -> void
      def return_validation_responses: (::Itly::Event event, untyped result) -> ::Itly::ValidationResponse?
      def deeply_stringify_keys: (::Hash[::String | ::Symbol, untyped] hash) -> ::Hash[::String, untyped]
      def hash_to_message: (::Hash[::String | ::Symbol, untyped] hash) -> ::String
    end
  end
end
