class Itly
  class Plugin
    class Iteratively < Plugin
      VERSION: ::String

      attr_reader logger: ::Logger
      attr_reader disabled: bool
      attr_reader client: ::Itly::Plugin::Iteratively::Client?
      attr_reader url: ::String
      attr_reader api_key: ::String

      def load: (options: ::Itly::PluginOptions options) -> void
      def post_identify: (user_id: ::String user_id, properties: ::Itly::Event properties, validation_results: ::Array[::Itly::ValidationResponse] validation_results) -> void
      def post_group: (user_id: ::String user_id, group_id: ::String group_id, properties: ::Itly::Event properties, validation_results: ::Array[::Itly::ValidationResponse] validation_results) -> void
      def post_track: (user_id: ::String user_id, event: ::Itly::Event event, validation_results: ::Array[::Itly::ValidationResponse] validation_results) -> void
      def flush: () -> void
      def shutdown: (?force: bool force) -> void

      private

      def initialize: (url: ::String url, api_key: ::String api_key, ?disabled: bool disabled, ?buffer_size: ::Integer buffer_size, ?max_retries: ::Integer max_retries, ?retry_delay_min: ::Float retry_delay_min, ?retry_delay_max: ::Float retry_delay_max, ?omit_values: bool omit_values) -> void
      def enabled?: () -> bool
      def client_track: (::String `type`, ::Itly::Event event, ::Array[::Itly::ValidationResponse]? validations) -> void
    end
  end
end
