class Itly
  class PluginIteratively < Plugin
    VERSION: ::String

    attr_reader logger: ::Logger
    attr_reader disabled: bool
    attr_reader client: ::Itly::PluginIteratively::Client
    attr_reader url: ::String
    attr_reader api_key: ::String

    def load: (options: ::Itly::Options options) -> void
    def post_identify: (user_id: ::String user_id, properties: ::Itly::Event properties, validation_results: ::Array[::Itly::ValidationResponse] validation_results) -> void
    def post_group: (user_id: ::String user_id, group_id: ::String group_id, properties: ::Itly::Event properties, validation_results: ::Array[::Itly::ValidationResponse] validation_results) -> void
    def post_track: (user_id: ::String user_id, event: ::Itly::Event event, validation_results: ::Array[::Itly::ValidationResponse] validation_results) -> void

    private

    def initialize: (url: ::String url, api_key: ::String api_key) -> void
    def enabled?: () -> bool
    def client_track: (::String `type`, ::Itly::Event properties, ::Array[::Itly::ValidationResponse]? validations) -> void
  end
end
