class Itly
  class Event
    attr_accessor name: ::String
    attr_accessor properties: ::Hash[::String | ::Symbol, ::String]
    attr_accessor id: ::String?
    attr_accessor version: ::String?
    attr_accessor metadata: ::Hash[::String | ::Symbol, ::String]?

    def to_s: () -> ::String
    def ==: (untyped other) -> untyped

    private

    def initialize: (name: ::String name, ?properties: ::Hash[::String | ::Symbol, ::String] properties, ?id: ::String? id, ?version: ::String? version, ?metadata: ::Hash[::String | ::Symbol, ::String]? metadata) -> void
  end
end
