class Itly
  class Options
    attr_accessor disabled: bool
    attr_accessor logger: ::Logger
    attr_accessor plugins: ::Array[::Itly::Plugin]
    attr_reader context: ::Itly::Event?
    attr_reader environment: ::Symbol
    attr_reader default_environment: bool
    attr_writer validation: ::Integer

    def for_plugin: () -> ::Itly::PluginOptions
    def context=: (::Hash[::String | ::Symbol, untyped] properties) -> void
    def environment=: (::Symbol value) -> void
    def validation: () -> ::Integer
    def development?: () -> bool
    def production?: () -> bool

    private

    def initialize: () -> void
  end
end
