class Itly
  class Options
    attr_accessor disabled: bool
    attr_accessor environment: ::Symbol
    attr_accessor logger: ::Logger
    attr_reader context: ::Itly::Event?
    attr_reader plugins: ::Itly::OptionsWrapper
    attr_writer validation: ::Integer

    def context=: (::Hash[::String | ::Symbol, untyped] properties) -> void
    def validation: () -> ::Integer
    def development?: () -> bool
    def production?: () -> bool

    private

    def initialize: () -> void
  end
end
