class Itly
  class Plugin::Mixpanel < Plugin
    VERSION: ::String

    attr_reader client: ::Mixpanel::Tracker?
    attr_reader disabled: bool

    def load: (options: ::Itly::PluginOptions options) -> void
    def identify: (user_id: ::String user_id, properties: propertiesHash properties, ?options: ::Itly::Plugin::Mixpanel::IdentifyOptions? options) -> void
    def track: (user_id: ::String user_id, event: ::Itly::Event event, ?options: ::Itly::Plugin::Mixpanel::TrackOptions? options) -> void
    def alias: (user_id: ::String user_id, previous_id: ::String previous_id, ?options: ::Itly::Plugin::Mixpanel::AliasOptions? options) -> void

    private

    def initialize: (project_token: ::String project_token, ?disabled: bool disabled) -> void
    def enabled?: () -> bool
  end
end
