class Itly
  class Plugin
    class Testing < Plugin
      VERSION: String

      attr_reader logger: Logger?
      attr_reader disabled: bool

      def load: (options: Itly::PluginOptions options) -> void
      def reset: () -> void
      def all: (?user_id: String? user_id) -> Array[Itly::Event]
      def of_type: (class_name: Class class_name, ?user_id: String? user_id) -> Array[Itly::Event]
      def first_of_type: (class_name: Class class_name, ?user_id: String? user_id) -> Itly::Event?

      def alias: (user_id: String user_id, previous_id: String previous_id, ?options: Itly::PluginCallOptions? options) -> void
      def identify: (user_id: String user_id, properties: propertiesHash properties, ?options: Itly::PluginCallOptions? options) -> void
      def group: (user_id: String user_id, group_id: String group_id, properties: propertiesHash properties, ?options: Itly::PluginCallOptions? options) -> void
      def track: (user_id: String user_id, event: Itly::Event event, ?options: Itly::PluginCallOptions? options) -> void

      private

      def initialize: (?disabled: bool disabled) -> void
      def enabled?: () -> bool
      def track_calls: (String method_name, Hash[Symbol, untyped] args) -> void
    end
  end
end
