class Itly
  class Plugin
    class Segment < Plugin
      VERSION: ::String

      attr_reader logger: ::Logger
      attr_reader client: ::SimpleSegment::Client?
      attr_reader write_key: ::String

      def load: (options: ::Hash[::Symbol, ::Symbol | ::Logger] options) -> void
      def identify: (user_id: ::String user_id, properties: ::Itly::Event properties) -> void
      def group: (user_id: ::String user_id, group_id: ::String group_id, properties: ::Itly::Event properties) -> void
      def track: (user_id: ::String user_id, event: ::Itly::Event event) -> void
      def alias: (user_id: ::String user_id, previous_id: ::String previous_id) -> void

      private

      def initialize: (write_key: ::String write_key, ?disabled: bool disabled) -> void
    end
  end
end
