# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in itly-sdk.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rbs', '~> 1.0'
gem 'rspec'
gem 'steep', '~> 0.41'
