# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in itly-plugin-segment.gemspec
gemspec

gem 'rake', '~> 13.0'

# TODO: before publication to RubyGems, switch to version 1

if ENV['LOCAL_ITLY_GEM']
  gem 'itly-sdk', '~> 0.1', path: '../sdk'
else
  gem 'itly-sdk', '~> 0.1'
end
