name: Ruby Gem

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Publish gems
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Publish itly-sdk to RubyGems
      run: ruby bin/publish_gems.rb sdk
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Publish plugin-amplitude to RubyGems
      run: ruby bin/publish_gems.rb amplitude
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Publish plugin-iteratively to RubyGems
      run: ruby bin/publish_gems.rb iteratively
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Publish plugin-mixpanel to RubyGems
      run: ruby bin/publish_gems.rb mixpanel
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Publish plugin-schema-validator to RubyGems
      run: ruby bin/publish_gems.rb schema-validator
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Publish plugin-segment to RubyGems
      run: ruby bin/publish_gems.rb segment
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
