name: Test and lint

on: [push, pull_request]

jobs:
  rspec-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for SDK
      run: cd sdk; bundle install

    - name: Run tests for SDK
      run: cd sdk; bin/rspec

  rspec-plugin-amplitude:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for Plugin::Amplitude
      run: |
        cd sdk; bundle install
        cd ../plugin-amplitude; LOCAL_ITLY_GEM=true bundle install
    - name: Run tests for Plugin::Amplitude
      run: cd plugin-amplitude; LOCAL_ITLY_GEM=true bin/rspec

  rspec-plugin-mixpanel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for Plugin::Mixpanel
      run: |
        cd sdk; bundle install
        cd ../plugin-mixpanel; LOCAL_ITLY_GEM=true bundle install
    - name: Run tests for Plugin::Mixpanel
      run: cd plugin-mixpanel; LOCAL_ITLY_GEM=true bin/rspec

  rspec-plugin-schema-validator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for Plugin::SchemaValidator
      run: |
        cd sdk; bundle install
        cd ../plugin-schema-validator; LOCAL_ITLY_GEM=true bundle install
    - name: Run tests for Plugin::SchemaValidator
      run: cd plugin-schema-validator; LOCAL_ITLY_GEM=true bin/rspec

  rspec-plugin-segment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for Plugin::Segment
      run: |
        cd sdk; bundle install
        cd ../plugin-segment; LOCAL_ITLY_GEM=true bundle install
    - name: Run tests for Plugin::Segment
      run: cd plugin-segment; LOCAL_ITLY_GEM=true bin/rspec

  rspec-plugin-snowplow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for Plugin::Snowplow
      run: |
        cd sdk; bundle install
        cd ../plugin-snowplow; LOCAL_ITLY_GEM=true bundle install
    - name: Run tests for Plugin::Snowplow
      run: cd plugin-snowplow; LOCAL_ITLY_GEM=true bin/rspec

  rspec-plugin-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems for Plugin::Snowplow
      run: |
        cd sdk; bundle install
        cd ../plugin-testing; LOCAL_ITLY_GEM=true bundle install
    - name: Run tests for Plugin::Testing
      run: cd plugin-testing; LOCAL_ITLY_GEM=true bin/rspec

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '2.6'

    - name: Install RuboCop
      run: gem install rubocop

    - name: Lint
      run: rubocop
