name: Test and lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Rubocop gem
        run: gem install rubocop

      - name: Run Rubocop
        run: rubocop
